# Generated by Django 3.2.12 on 2022-05-04 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atracoes', '0001_initial'),
        ('comentarios', '0003_alter_comentario_comentario'),
        ('core', '0003_pontoturistico_comentarios'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pontoturistico',
            name='atracoes',
            field=models.ManyToManyField(blank=True, to='atracoes.Atracao', verbose_name='Atrações'),
        ),
        migrations.AlterField(
            model_name='pontoturistico',
            name='comentarios',
            field=models.ManyToManyField(blank=True, to='comentarios.Comentario', verbose_name='Comentários'),
        ),
    ]
