# Generated by Django 3.2.12 on 2022-05-04 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avaliacoes', '0001_initial'),
        ('core', '0004_auto_20220504_0617'),
    ]

    operations = [
        migrations.AddField(
            model_name='pontoturistico',
            name='avaliacoes',
            field=models.ManyToManyField(blank=True, to='avaliacoes.Avaliacao', verbose_name='Avaliações'),
        ),
    ]
