# Generated by Django 3.2.12 on 2022-05-04 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('linha1', models.CharField(max_length=100, verbose_name='Linha 1')),
                ('linha2', models.CharField(blank=True, max_length=100, null=True, verbose_name='Linha 2')),
                ('cidade', models.CharField(max_length=100, verbose_name='Cidade')),
                ('estado', models.CharField(max_length=100, verbose_name='Estado')),
                ('pais', models.CharField(max_length=100, verbose_name='País')),
                ('latitude', models.BigIntegerField(blank=True, null=True, verbose_name='Latitude')),
                ('longitude', models.BigIntegerField(blank=True, null=True, verbose_name='Longitude')),
            ],
            options={
                'verbose_name': 'Endereço',
                'verbose_name_plural': 'Endereços',
            },
        ),
    ]
