# Generated by Django 3.2.12 on 2022-05-03 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Atracao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('horario_abertura', models.TimeField(verbose_name='Horário de abertura')),
                ('horario_fechamento', models.TimeField(verbose_name='Horário de fechamento')),
                ('idade_minima', models.PositiveIntegerField(verbose_name='Idade mínima')),
            ],
            options={
                'verbose_name': 'Atração',
                'verbose_name_plural': 'Atrações',
            },
        ),
    ]
